### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ashtonaut** [gbale/Uwp.GPhotos#1]
Hi there, how do I install this app in Windows 10? Do I need to compile/create an APPX package myself?

**Comment by gbale** [comment]
Correct, will need to build and run using VS2015 or later.

Or can create something similar at
https://appstudio.windows.com with no coding req'd - the start page and include rule URIs in Package.appmanifest might be helpful if going that route.

From: ashtonaut
Sent: Thursday, December 29, 4:48 PM
Subject: [gbale/Uwp.GPhotos] Installation (#1)
To: gbale/Uwp.GPhotos
Cc: Subscribed

Hi there, how do I install this app in Windows 10? Do I need to compile/create an APPX package myself?

-
